# ProBot Request Info (https://probot.github.io/apps/request-info/)

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more information about this
  issue/PR.\n\n![](https://feross.net/s/cats/14.gif)

# ProBot Welcome (https://probot.github.io/apps/welcome/)

newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.
  ![](https://feross.net/s/cats/9.gif)
firstPRMergeComment: >
  Congrats on getting your first pull request merged!
  ![](https://feross.net/s/cats/29.gif)
