# ProBot Stale (https://probot.github.io/apps/stale/)

daysUntilStale: 120
daysUntilClose: 7
exemptLabels:
  - accepted
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions. <br><br> ![](https://feross.net/s/cats/18.gif)
closeComment: false
