browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: microsoftedge
    version: latest
  - name: android
    version: latest
  - name: iphone
    version: latest
providers:
  - airtap-sauce
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
