# Explicitly ensure line endings aren't mangled
# http://www.appveyor.com/docs/lang/nodejs-iojs#line-endings
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js
# https://www.appveyor.com/docs/lang/nodejs-iojs#testing-under-multiple-versions-of-node-js-or-io-js
environment:
  matrix:
  - nodejs_version: "6"
  - nodejs_version: "5"
  - nodejs_version: "4"

platform:
  - x86

# Install scripts. (runs after repo cloning)
install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs#installing-em-any-em-version-of-node-js-or-io-js
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm run test-node # (not `npm test`, because saucelabs tests run via Travis)

# Don't actually build.
# https://www.appveyor.com/docs/lang/nodejs-iojs#quick-start
build: off
